# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'racer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for racer

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTGeolocation',
]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  target 'racer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'racerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

